#In this notebook, we're going to cover some of the most fundamental concepts of tensors using TensoFlow


* Introduction to tensors
* Getting information from tensors
* Manipulation tensors
* Tensors & NumPy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercises to try for yourself!

 ## Introduction to Tensors

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.9.2


In [2]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([19,19,19])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([19, 19, 19], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
# Create the matrix which has more than 1 dimension
matrix = tf.constant([[[1,19,27], [19,27,1] ,[27,19,1]],[[1,19,27], [19,27,1] ,[27,19,1]]])
matrix

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 1, 19, 27],
        [19, 27,  1],
        [27, 19,  1]],

       [[ 1, 19, 27],
        [19, 27,  1],
        [27, 19,  1]]], dtype=int32)>

In [7]:
matrix.ndim

3

In [8]:
matrix2 = tf.constant([[1.,19.], [19.,1.],[27.,19.]], dtype=tf.float16)
matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 1., 19.],
       [19.,  1.],
       [27., 19.]], dtype=float16)>

In [9]:
matrix2.ndim

2

In [10]:
# Let's create a tensor
tensor = tf.constant([[[1,2,3],[4,5,6]],
                      [[7,8,9],[10,11,12]],
                      [[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

# What we've created so far:
* Scalar: a single number
* Vector: a number with direction(eg, wind speed and direction)
* Matrix: a two-dimensional array of numbers
* Tensor: an n-dimenisonal array of numbers (n can be any numbers, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

### Creating tensors with 'tf.Variable'

In [12]:
# Create the same Tensor with tf.Variable() as above
changeable_tensor = tf.Variable([6,19])
unchangeable_tensor = tf.constant([6,19])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 6, 19], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 6, 19], dtype=int32)>)

In [13]:
# Let's try change one of the elements in our changeable tensor
# How about try with .assign()
changeable_tensor[0].assign(19)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([19, 19], dtype=int32)>

### Creating random tensors

In [14]:
 # Create two random tensor (but the same)
random_1 = tf.random.Generator.from_seed(10) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(10) # set seed for reproducibility
random_2 = random_2.normal(shape=(3,2))

# check two random equal or not
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.29604465, -0.21134207],
        [ 0.01063002,  1.5165398 ],
        [ 0.2730574 , -0.29925638]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.29604465, -0.21134207],
        [ 0.01063002,  1.5165398 ],
        [ 0.2730574 , -0.29925638]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [15]:
# Shuffle a tensor
not_shuffled = tf.constant([[[2,1],[22,11]],[[4,3],[44,33]],[[6,5],[66,55]]])
not_shuffled.ndim

3

In [16]:
#not_shuffled
#tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 6,  5],
        [66, 55]],

       [[ 4,  3],
        [44, 33]],

       [[ 2,  1],
        [22, 11]]], dtype=int32)>

#### *if we want shuffled tensors to be in the same order, we've got to use the global level random seed as well as the operation level random seed*

### Other ways to make tensors

In [17]:
# Create a tensor of all ones
tf.ones([4,3, 2], dtype=tf.int32)

<tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]], dtype=int32)>

In [18]:
# Create a tensor of all zeros
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors
The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU computing.

In [19]:
# turn NumPy arrays into tensors
import numpy as np
numpyA = np.arange(1,25,dtype=np.int32)
numpyA

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [20]:
A = tf.constant(numpyA, shape=(6,4))
B = tf.constant(numpyA)
A, B, A.ndim

(<tf.Tensor: shape=(6, 4), dtype=int32, numpy=
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 2)

In [21]:
A.ndim

2

### Getting information from tensors
When dealing with tensors we probably want to be aware of the following attributes:
* Shape
* Rank
* Axis or dimension
* Size

In [22]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [23]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [24]:
# Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shap of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shap of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: 120


### Indexing tensors
Tensors can be indexed just like Python lists.

In [25]:
# Get the first 2 elements of each dimensiion
rank_4_tensor[:2,:2,:2,:3]
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [26]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [27]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[6,10], [19,27]])
rank_2_tensor, rank_2_tensor.shape, rank_2_tensor.ndim

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 6, 10],
        [19, 27]], dtype=int32)>, TensorShape([2, 2]), 2)

In [28]:
some_list = [1,2,3,4]
some_list, some_list[-1]

([1, 2, 3, 4], 4)

In [29]:
# Get the last item of each of row of our rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 27], dtype=int32)>

In [30]:
# Add in extra dimension to rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 6],
        [10]],

       [[19],
        [27]]], dtype=int32)>

In [31]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # -1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 6],
        [10]],

       [[19],
        [27]]], dtype=int32)>

In [32]:
tf.expand_dims(rank_2_tensor, axis=0)
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6, 10],
       [19, 27]], dtype=int32)>

### Manipulating tensors (tensor operations)
**Basic operations**

In [33]:
# We can add values to a tensor using the addition, multiplication, Extraction & Dividion
tensor = tf.constant([[6,10],[19,27]])
print("Original Tensor:", tensor)
print("Additional Tensor:", tensor + 10)
print("Extraction Tensor:", tensor - 10)
print("Multiplication Tensor:", tensor * 10)
print("Dividion Tensor:", tensor / 10)

Original Tensor: tf.Tensor(
[[ 6 10]
 [19 27]], shape=(2, 2), dtype=int32)
Additional Tensor: tf.Tensor(
[[16 20]
 [29 37]], shape=(2, 2), dtype=int32)
Extraction Tensor: tf.Tensor(
[[-4  0]
 [ 9 17]], shape=(2, 2), dtype=int32)
Multiplication Tensor: tf.Tensor(
[[ 60 100]
 [190 270]], shape=(2, 2), dtype=int32)
Dividion Tensor: tf.Tensor(
[[0.6 1. ]
 [1.9 2.7]], shape=(2, 2), dtype=float64)


In [34]:
tf.add(tensor, 10 )

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[16, 20],
       [29, 37]], dtype=int32)>

### Matrix multiplication
In machine learning, matrix multiplication is one of the most common tensor operations.

In [35]:
# Matrix multiplication in tensorflow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[ 6 10]
 [19 27]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[226, 330],
       [627, 919]], dtype=int32)>

In [36]:
# Matrix multplication with Python operator "@"
tensor @ tensor 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[226, 330],
       [627, 919]], dtype=int32)>

In [37]:
# Create a tensor (3,2) matrix
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
# Create another (3,2) matrix
Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])

X, Y,tf.transpose(X), tf.matmul(tf.transpose(X), Y)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 89,  98],
        [116, 128]], dtype=int32)>)

***The dot product***
#####Matrix multiplication is also referrred to as the dot product.
You can perform matrix multiplication using:
* tf.matmul()
* tf.tensordot()

In [38]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [39]:
# Perform the dot product on X and Y (requires X or Y to be transposed)
tf.tensordot(X, tf.transpose(Y), axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [40]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [41]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape=[2,3]))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

### Changing the datatype of a tensor


In [42]:
# Create a new tensor with default datatype (float32)(int32)
BFloat = tf.constant([6.1, 19.27])
BInt = tf.constant([6,10])
BFloat, BFloat.dtype, BInt, BInt.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 6.1 , 19.27], dtype=float32)>,
 tf.float32,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 6, 10], dtype=int32)>,
 tf.int32)

In [43]:
# Change from float32 to float16 and int32 to int16 (reduced precision)
CFloat = tf.cast(BFloat, dtype=tf.float16)
CInt = tf.cast(BInt, dtype=tf.int16)
D = tf.cast(BInt, dtype=tf.float16)
CFloat, CInt, D

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 6.1 , 19.27], dtype=float16)>,
 <tf.Tensor: shape=(2,), dtype=int16, numpy=array([ 6, 10], dtype=int16)>,
 <tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 6., 10.], dtype=float16)>)

### Aggregating Tensors

Aggregating tensor = condensing them from multiple values down to a smaller amount of values

In [44]:
# Get the absolute values
AA = tf.constant([-6,-10])
tf.abs(AA) # absolute values


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 6, 10], dtype=int32)>

### We will go through the following forms of aggregation:
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tenso

In [45]:
# Create a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0,100, size=50))
E


<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([84, 11, 66, 78,  6, 87, 33, 21, 33, 95,  1,  6, 98, 79, 34, 61, 31,
       78, 61, 96, 56, 75,  2, 70,  5, 83, 10, 89, 65, 64, 73, 79, 25, 40,
       98, 39, 99, 91, 30, 43, 46, 74, 24,  9, 61, 89, 10,  9, 95, 16])>

In [46]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [47]:
# Get the minimum
tf.reduce_min(E), np.min(E)

(<tf.Tensor: shape=(), dtype=int64, numpy=1>, 1)

In [48]:
# Get the maximum
tf.reduce_max(E) , np.max(E)

(<tf.Tensor: shape=(), dtype=int64, numpy=99>, 99)

In [49]:
# Get the mean
tf.reduce_mean(E) , np.mean(E)

(<tf.Tensor: shape=(), dtype=int64, numpy=52>, 52.56)

In [50]:
# Get the sum
tf.reduce_sum(E) , np.sum(E)

(<tf.Tensor: shape=(), dtype=int64, numpy=2628>, 2628)

In [51]:
# Get the variance
EFloat = tf.cast(E, dtype=tf.float16)
tf.math.reduce_variance(EFloat)

<tf.Tensor: shape=(), dtype=float16, numpy=1030.0>

In [52]:
# Get the standard variation
EFloat = tf.cast(E, dtype=tf.float16)
tf.math.reduce_std(EFloat)

<tf.Tensor: shape=(), dtype=float16, numpy=32.1>

### Find the positional maximum and minimum

In [53]:
# Create a new tensor for finding positional minimum and maxmimum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [54]:
# Find the positional maximum, minimum
tf.argmax(F), tf.argmin(F),F[tf.argmax(F)], F[tf.argmin(F)]


(<tf.Tensor: shape=(), dtype=int64, numpy=42>,
 <tf.Tensor: shape=(), dtype=int64, numpy=16>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>)

In [55]:
# Find the max, min value of F
tf.reduce_max(F), tf.reduce_min(F)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>)

In [56]:
# Check for equality
F[tf.argmax(F)] == tf.reduce_max(F), F[tf.argmin(F)] == tf.reduce_min(F)

(<tf.Tensor: shape=(), dtype=bool, numpy=True>,
 <tf.Tensor: shape=(), dtype=bool, numpy=True>)

### Squeezing a tensor (removing all single dimensions)

In [57]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [58]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [59]:
GSqueezed = tf.squeeze(G)
GSqueezed, GSqueezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

### One-hot encoding tensors

In [60]:
# Create a list of indices
some_list = [0,1,2,3,4] # could be red, green, blue, purple

# create one-hot encoding list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

In [61]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="ON", off_value="Off")

<tf.Tensor: shape=(5, 4), dtype=string, numpy=
array([[b'ON', b'Off', b'Off', b'Off'],
       [b'Off', b'ON', b'Off', b'Off'],
       [b'Off', b'Off', b'ON', b'Off'],
       [b'Off', b'Off', b'Off', b'ON'],
       [b'Off', b'Off', b'Off', b'Off']], dtype=object)>

### Squaring, log , Square root

In [62]:
# Create a new Tensor
H = tf.range(1,10)
H, tf.square(H), tf.math.sqrt(tf.cast(H, dtype=tf.float16)), tf.math.log(tf.cast(H, dtype=tf.float16)) 

(<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>,
 <tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>,
 <tf.Tensor: shape=(9,), dtype=float16, numpy=
 array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
       dtype=float16)>,
 <tf.Tensor: shape=(9,), dtype=float16, numpy=
 array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
        2.197 ], dtype=float16)>)

### Tensors and NumPy

TensorFlow interacts beautifully with NumPy arrays

In [63]:
# Create a tensor directly from a NumPy array
J = tf.constant(np.array([1., 3., 9.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 3., 9.])>

In [64]:
# convert tensor bach to numpy array
np.array(J), type(np.array(J)), J.numpy(), type(J.numpy())

(array([1., 3., 9.]), numpy.ndarray, array([1., 3., 9.]), numpy.ndarray)

In [65]:
# the default types of each are slightly different
numpy_J = tf.constant(np.array([1., 3., 9.]))
tensor_J = tf.constant([1., 3., 9.])
# check the datatypes of data
numpy_J, numpy_J.dtype, tensor_J, tensor_J.dtype

(<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 3., 9.])>,
 tf.float64,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 3., 9.], dtype=float32)>,
 tf.float32)

### Finding access to GPUS
* If you have access to a CUDA-enabled GPU, TensorFlow will automatically use it whenever possible.

In [66]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [67]:
!nvidia-smi

Mon Oct 24 05:31:18 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   53C    P0    29W /  70W |    314MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------